In [1]:
%pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

Looking in indexes: https://download.pytorch.org/whl/cu124Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
%pip install transformers pandas numpy requests beautifulsoup4


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import requests
from bs4 import BeautifulSoup
import re


d:\Codes\tcc-sentiment-analysis\nlpvenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## Instanciate Model

In [4]:
tokenizer = AutoTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

model = AutoModelForSequenceClassification.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

d:\Codes\tcc-sentiment-analysis\nlpvenv\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [5]:
bad_tokens = tokenizer.encode('I hate this, absolutely the worst', return_tensors='pt')
bad_tokens

tensor([[  101,   151, 39487, 10372,   117, 35925, 10563, 10103, 43060,   102]])

---

Mostrando como decodificar de volta para o texto

In [6]:
tokenizer.decode(bad_tokens[0])

'[CLS] i hate this, absolutely the worst [SEP]'

---

In [7]:
results = model(bad_tokens)
results.logits

tensor([[ 5.0607,  1.6029, -1.0123, -3.0154, -1.8469]],
       grad_fn=<AddmmBackward0>)

In [8]:
int(torch.argmax(results.logits))

0

---

---

### Exemplo comparativo de tokens para mesma frase com sentimento invertido

In [9]:
good_tokens = tokenizer.encode('I love this, absolutely the best', return_tensors='pt')
good_tokens

tensor([[  101,   151, 11157, 10372,   117, 35925, 10563, 10103, 11146,   102]])

In [10]:
good_results = model(good_tokens)
good_results.logits

tensor([[-2.3337, -2.5702, -1.3826,  1.0607,  4.3989]],
       grad_fn=<AddmmBackward0>)

In [11]:
int(torch.argmax(good_results.logits))

4